-- MySQL export generated from SQLite on 2026-03-20
SET NAMES utf8mb4;
SET foreign_key_checks = 0;

CREATE TABLE IF NOT EXISTS `migrations` (`id` integer primary key AUTO_INCREMENT not null, `migration` varchar(255) not null, `batch` integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2026_03_14_015940_create_managers_table',2);
INSERT INTO migrations VALUES(5,'2026_03_14_015941_create_roles_table',2);
INSERT INTO migrations VALUES(6,'2026_03_14_015941_create_stores_table',2);
INSERT INTO migrations VALUES(7,'2026_03_14_015942_create_categories_table',2);
INSERT INTO migrations VALUES(8,'2026_03_14_015942_create_customers_table',2);
INSERT INTO migrations VALUES(9,'2026_03_14_015942_create_devices_table',2);
INSERT INTO migrations VALUES(10,'2026_03_14_015942_create_permissions_table',2);
INSERT INTO migrations VALUES(11,'2026_03_14_015942_create_products_table',2);
INSERT INTO migrations VALUES(12,'2026_03_14_015943_create_payment_methods_table',2);
INSERT INTO migrations VALUES(13,'2026_03_14_015943_create_product_variants_table',2);
INSERT INTO migrations VALUES(14,'2026_03_14_015943_create_sales_table',2);
INSERT INTO migrations VALUES(15,'2026_03_14_015944_create_device_sync_logs_table',2);
INSERT INTO migrations VALUES(16,'2026_03_14_015944_create_discounts_table',2);
INSERT INTO migrations VALUES(17,'2026_03_14_015944_create_payments_table',2);
INSERT INTO migrations VALUES(18,'2026_03_14_015944_create_sale_items_table',2);
INSERT INTO migrations VALUES(19,'2026_03_14_015944_create_stock_movements_table',2);
INSERT INTO migrations VALUES(20,'2026_03_14_015944_create_taxes_table',2);
INSERT INTO migrations VALUES(21,'2026_03_14_015945_create_permission_role_table',2);
INSERT INTO migrations VALUES(22,'2026_03_14_015945_create_role_user_table',2);
INSERT INTO migrations VALUES(23,'2026_03_14_020207_add_manager_fields_to_users_table',2);
INSERT INTO migrations VALUES(24,'2026_03_14_020434_add_tax_fk_to_products_table',2);
INSERT INTO migrations VALUES(25,'2026_03_14_030510_create_personal_access_tokens_table',2);
INSERT INTO migrations VALUES(26,'2026_03_16_000001_add_ingredients_and_image_to_products_table',2);
INSERT INTO migrations VALUES(27,'2026_03_17_000001_create_currencies_table',2);
INSERT INTO migrations VALUES(28,'2026_03_17_000002_add_currency_to_stores_table',2);
INSERT INTO migrations VALUES(29,'2026_03_18_000001_create_ingredients_table',2);
INSERT INTO migrations VALUES(30,'2026_03_18_000002_create_ingredient_product_table',2);
INSERT INTO migrations VALUES(31,'2026_03_18_000003_add_ingredients_to_sale_items_table',2);
INSERT INTO migrations VALUES(32,'2026_03_20_000001_create_plans_table',2);
INSERT INTO migrations VALUES(33,'2026_03_20_000002_create_ingredient_categories_table',2);
INSERT INTO migrations VALUES(34,'2026_03_20_000003_add_plan_id_to_managers_table',2);
INSERT INTO migrations VALUES(35,'2026_03_20_000004_add_image_path_to_categories_table',2);
INSERT INTO migrations VALUES(36,'2026_03_20_000005_add_category_and_image_to_ingredients_table',2);
INSERT INTO migrations VALUES(37,'2026_03_20_000006_add_logo_to_stores_table',2);
INSERT INTO migrations VALUES(38,'2026_03_20_000007_add_image_url_to_products_table',2);
CREATE TABLE IF NOT EXISTS `password_reset_tokens` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` datetime, primary key (`email`));
CREATE TABLE IF NOT EXISTS `sessions` (`id` varchar(255) not null, `user_id` integer, `ip_address` varchar(255), `user_agent` text, `payload` text not null, `last_activity` integer not null, primary key (`id`));
CREATE TABLE IF NOT EXISTS `cache` (`key` varchar(255) not null, `value` text not null, `expiration` integer not null, primary key (`key`));
CREATE TABLE IF NOT EXISTS `cache_locks` (`key` varchar(255) not null, `owner` varchar(255) not null, `expiration` integer not null, primary key (`key`));
CREATE TABLE IF NOT EXISTS `jobs` (`id` integer primary key AUTO_INCREMENT not null, `queue` varchar(255) not null, `payload` text not null, `attempts` integer not null, `reserved_at` integer, `available_at` integer not null, `created_at` integer not null);
CREATE TABLE IF NOT EXISTS `job_batches` (`id` varchar(255) not null, `name` varchar(255) not null, `total_jobs` integer not null, `pending_jobs` integer not null, `failed_jobs` integer not null, `failed_job_ids` text not null, `options` text, `cancelled_at` integer, `created_at` integer not null, `finished_at` integer, primary key (`id`));
CREATE TABLE IF NOT EXISTS `failed_jobs` (`id` integer primary key AUTO_INCREMENT not null, `uuid` varchar(255) not null, `connection` text not null, `queue` text not null, `payload` text not null, `exception` text not null, `failed_at` datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS `roles` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer, `name` varchar(255) not null, `description` varchar(255), `is_system` tinyint(1) not null default '0', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `categories` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer, `parent_id` integer, `name` varchar(255) not null, `is_active` tinyint(1) not null default '1', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, `image_path` varchar(255), foreign key(`manager_id`) references `managers`(`id`) on delete set null, foreign key(`parent_id`) references `categories`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `customers` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer not null, `name` varchar(255) not null, `email` varchar(255), `phone` varchar(255), `address` varchar(255), `note` text, `is_active` tinyint(1) not null default '1', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete cascade);
CREATE TABLE IF NOT EXISTS `devices` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer not null, `store_id` integer not null, `uuid` varchar(255) not null, `name` varchar(255) not null, `type` varchar(255) not null default 'pos', `platform` varchar(255) not null default 'android', `secret` varchar(255) not null, `last_seen_at` datetime, `last_sync_at` datetime, `is_active` tinyint(1) not null default '1', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete cascade, foreign key(`store_id`) references `stores`(`id`) on delete cascade);
CREATE TABLE IF NOT EXISTS `permissions` (`id` integer primary key AUTO_INCREMENT not null, `name` varchar(255) not null, `description` varchar(255), `created_at` datetime, `updated_at` datetime, `deleted_at` datetime);
CREATE TABLE IF NOT EXISTS `payment_methods` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer, `name` varchar(255) not null, `type` varchar(255) not null default 'cash', `is_active` tinyint(1) not null default '1', `is_default` tinyint(1) not null default '0', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `product_variants` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer not null, `product_id` integer not null, `uuid` varchar(255) not null, `name` varchar(255) not null, `sku` varchar(255), `barcode` varchar(255), `price` numeric, `is_active` tinyint(1) not null default '1', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete cascade, foreign key(`product_id`) references `products`(`id`) on delete cascade);
CREATE TABLE IF NOT EXISTS `sales` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer not null, `store_id` integer not null, `device_id` integer, `user_id` integer, `customer_id` integer, `number` varchar(255), `status` varchar(255) not null default 'paid', `subtotal` numeric not null default '0', `discount_total` numeric not null default '0', `tax_total` numeric not null default '0', `grand_total` numeric not null default '0', `currency` varchar(255) not null default 'USD', `note` text, `ordered_at` datetime, `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete cascade, foreign key(`store_id`) references `stores`(`id`) on delete cascade, foreign key(`device_id`) references `devices`(`id`) on delete set null, foreign key(`user_id`) references `users`(`id`) on delete set null, foreign key(`customer_id`) references `customers`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `device_sync_logs` (`id` integer primary key AUTO_INCREMENT not null, `device_id` integer not null, `direction` varchar(255) not null, `status` varchar(255) not null default 'ok', `payload_hash` varchar(255), `error_message` text, `synced_at` datetime, `created_at` datetime, `updated_at` datetime, foreign key(`device_id`) references `devices`(`id`) on delete cascade);
CREATE TABLE IF NOT EXISTS `discounts` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer, `name` varchar(255) not null, `type` varchar(255) not null default 'percent', `value` numeric not null default '0', `scope` varchar(255) not null default 'order', `is_active` tinyint(1) not null default '1', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `payments` (`id` integer primary key AUTO_INCREMENT not null, `sale_id` integer not null, `payment_method_id` integer not null, `amount` numeric not null default '0', `reference` varchar(255), `paid_at` datetime, `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`sale_id`) references `sales`(`id`) on delete cascade, foreign key(`payment_method_id`) references `payment_methods`(`id`) on delete cascade);
CREATE TABLE IF NOT EXISTS `sale_items` (`id` integer primary key AUTO_INCREMENT not null, `sale_id` integer not null, `product_id` integer, `product_variant_id` integer, `name` varchar(255) not null, `sku` varchar(255), `quantity` numeric not null default '1', `unit_price` numeric not null default '0', `discount_amount` numeric not null default '0', `tax_amount` numeric not null default '0', `total` numeric not null default '0', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, `ingredients` text, foreign key(`sale_id`) references `sales`(`id`) on delete cascade, foreign key(`product_id`) references `products`(`id`) on delete set null, foreign key(`product_variant_id`) references `product_variants`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `stock_movements` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer not null, `product_id` integer not null, `store_id` integer, `user_id` integer, `quantity` numeric not null, `type` varchar(255) not null default 'adjust', `reason` varchar(255), `ref_type` varchar(255), `ref_id` integer, `occurred_at` datetime, `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete cascade, foreign key(`product_id`) references `products`(`id`) on delete cascade, foreign key(`store_id`) references `stores`(`id`) on delete set null, foreign key(`user_id`) references `users`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `taxes` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer, `name` varchar(255) not null, `rate` numeric not null default '0', `type` varchar(255) not null default 'percent', `is_active` tinyint(1) not null default '1', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `permission_role` (`permission_id` integer not null, `role_id` integer not null, foreign key(`permission_id`) references `permissions`(`id`) on delete cascade, foreign key(`role_id`) references `roles`(`id`) on delete cascade, primary key (`permission_id`, `role_id`));
CREATE TABLE IF NOT EXISTS `role_user` (`role_id` integer not null, `user_id` integer not null, foreign key(`role_id`) references `roles`(`id`) on delete cascade, foreign key(`user_id`) references `users`(`id`) on delete cascade, primary key (`role_id`, `user_id`));
CREATE TABLE IF NOT EXISTS `users` (`id` integer primary key AUTO_INCREMENT not null, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` datetime, `password` varchar(255) not null, `remember_token` varchar(255), `created_at` datetime, `updated_at` datetime, `manager_id` integer, `store_id` integer, `is_super_admin` tinyint(1) not null default '0', `is_active` tinyint(1) not null default '1', `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete set null, foreign key(`store_id`) references `stores`(`id`) on delete set null);
INSERT INTO users VALUES(1,'admin','admin@kindpos.com','2026-03-20 19:54:56','$2y$12$IQjkgosaHBEhOohubek7MeIvSCLpUL952R6VD3TA29l26S6jC.AMG',NULL,'2026-03-20 19:54:56','2026-03-20 19:54:56',NULL,NULL,1,1,NULL);
CREATE TABLE IF NOT EXISTS `products` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer not null, `category_id` integer, `tax_id` integer, `uuid` varchar(255) not null, `name` varchar(255) not null, `sku` varchar(255), `barcode` varchar(255), `description` text, `price` numeric not null default ('0'), `cost` numeric not null default ('0'), `track_stock` tinyint(1) not null default ('1'), `is_active` tinyint(1) not null default ('1'), `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, `ingredients` text, `image_path` varchar(255), `image_url` varchar(255), foreign key(`category_id`) references categories(`id`) on delete set null on update no action, foreign key(`manager_id`) references managers(`id`) on delete cascade on update no action, foreign key(`tax_id`) references `taxes`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (`id` integer primary key AUTO_INCREMENT not null, `tokenable_type` varchar(255) not null, `tokenable_id` integer not null, `name` text not null, `token` varchar(255) not null, `abilities` text, `last_used_at` datetime, `expires_at` datetime, `created_at` datetime, `updated_at` datetime);
CREATE TABLE IF NOT EXISTS `currencies` (`id` integer primary key AUTO_INCREMENT not null, `name` varchar(255) not null, `code` varchar(255) not null, `symbol` varchar(255) not null, `is_active` tinyint(1) not null default '1', `created_at` datetime, `updated_at` datetime);
CREATE TABLE IF NOT EXISTS `stores` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer not null, `name` varchar(255) not null, `code` varchar(255), `phone` varchar(255), `email` varchar(255), `address` varchar(255), `stock_enabled` tinyint(1) not null default ('1'), `is_active` tinyint(1) not null default ('1'), `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, `currency_id` integer, `is_currency_right` tinyint(1) not null default '1', `logo_path` varchar(255), foreign key(`manager_id`) references managers(`id`) on delete cascade on update no action, foreign key(`currency_id`) references `currencies`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `ingredient_product` (`id` integer primary key AUTO_INCREMENT not null, `ingredient_id` integer not null, `product_id` integer not null, `quantity` numeric not null default '1', `created_at` datetime, `updated_at` datetime, foreign key(`ingredient_id`) references `ingredients`(`id`) on delete cascade, foreign key(`product_id`) references `products`(`id`) on delete cascade);
CREATE TABLE IF NOT EXISTS `plans` (`id` integer primary key AUTO_INCREMENT not null, `name` varchar(255) not null, `duration_days` integer, `max_stores` integer, `max_devices` integer, `is_active` tinyint(1) not null default '1', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime);
CREATE TABLE IF NOT EXISTS `ingredient_categories` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer, `name` varchar(255) not null, `is_active` tinyint(1) not null default '1', `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, foreign key(`manager_id`) references `managers`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `managers` (`id` integer primary key AUTO_INCREMENT not null, `name` varchar(255) not null, `slug` varchar(255) not null, `is_active` tinyint(1) not null default ('1'), `max_stores` integer, `max_devices` integer, `currency` varchar(255) not null default ('USD'), `timezone` varchar(255) not null default ('UTC'), `plan_name` varchar(255), `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, `plan_id` integer, foreign key(`plan_id`) references `plans`(`id`) on delete set null);
CREATE TABLE IF NOT EXISTS `ingredients` (`id` integer primary key AUTO_INCREMENT not null, `manager_id` integer, `name` varchar(255) not null, `is_active` tinyint(1) not null default ('1'), `created_at` datetime, `updated_at` datetime, `deleted_at` datetime, `ingredient_category_id` integer, `image_path` varchar(255), foreign key(`manager_id`) references managers(`id`) on delete set null on update no action, foreign key(`ingredient_category_id`) references `ingredient_categories`(`id`) on delete set null);
CREATE INDEX `sessions_user_id_index` on `sessions` (`user_id`);
CREATE INDEX `sessions_last_activity_index` on `sessions` (`last_activity`);
CREATE INDEX `cache_expiration_index` on `cache` (`expiration`);
CREATE INDEX `cache_locks_expiration_index` on `cache_locks` (`expiration`);
CREATE INDEX `jobs_queue_reserved_at_available_at_index` on `jobs` (`queue`, `reserved_at`, `available_at`);
CREATE UNIQUE INDEX `failed_jobs_uuid_unique` on `failed_jobs` (`uuid`);
CREATE UNIQUE INDEX `roles_manager_id_name_unique` on `roles` (`manager_id`, `name`);
CREATE UNIQUE INDEX `categories_manager_id_name_unique` on `categories` (`manager_id`, `name`);
CREATE INDEX `customers_manager_id_is_active_index` on `customers` (`manager_id`, `is_active`);
CREATE INDEX `devices_manager_id_store_id_is_active_index` on `devices` (`manager_id`, `store_id`, `is_active`);
CREATE UNIQUE INDEX `devices_uuid_unique` on `devices` (`uuid`);
CREATE UNIQUE INDEX `permissions_name_unique` on `permissions` (`name`);
CREATE UNIQUE INDEX `payment_methods_manager_id_name_unique` on `payment_methods` (`manager_id`, `name`);
CREATE UNIQUE INDEX `product_variants_manager_id_sku_unique` on `product_variants` (`manager_id`, `sku`);
CREATE UNIQUE INDEX `product_variants_manager_id_barcode_unique` on `product_variants` (`manager_id`, `barcode`);
CREATE INDEX `product_variants_manager_id_product_id_is_active_index` on `product_variants` (`manager_id`, `product_id`, `is_active`);
CREATE UNIQUE INDEX `product_variants_uuid_unique` on `product_variants` (`uuid`);
CREATE INDEX `sales_manager_id_store_id_status_index` on `sales` (`manager_id`, `store_id`, `status`);
CREATE INDEX `sales_manager_id_ordered_at_index` on `sales` (`manager_id`, `ordered_at`);
CREATE INDEX `device_sync_logs_device_id_direction_status_index` on `device_sync_logs` (`device_id`, `direction`, `status`);
CREATE UNIQUE INDEX `discounts_manager_id_name_unique` on `discounts` (`manager_id`, `name`);
CREATE INDEX `payments_sale_id_index` on `payments` (`sale_id`);
CREATE INDEX `sale_items_sale_id_index` on `sale_items` (`sale_id`);
CREATE INDEX `stock_movements_manager_id_product_id_type_index` on `stock_movements` (`manager_id`, `product_id`, `type`);
CREATE UNIQUE INDEX `taxes_manager_id_name_unique` on `taxes` (`manager_id`, `name`);
CREATE UNIQUE INDEX `users_email_unique` on `users` (`email`);
CREATE INDEX `users_manager_id_is_active_index` on `users` (`manager_id`, `is_active`);
CREATE INDEX `products_tax_id_index` on `products` (`tax_id`);
CREATE UNIQUE INDEX `products_manager_id_barcode_unique` on `products` (`manager_id`, `barcode`);
CREATE INDEX `products_manager_id_is_active_index` on `products` (`manager_id`, `is_active`);
CREATE UNIQUE INDEX `products_manager_id_sku_unique` on `products` (`manager_id`, `sku`);
CREATE UNIQUE INDEX `products_uuid_unique` on `products` (`uuid`);
CREATE INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` on `personal_access_tokens` (`tokenable_type`, `tokenable_id`);
CREATE UNIQUE INDEX `personal_access_tokens_token_unique` on `personal_access_tokens` (`token`);
CREATE INDEX `personal_access_tokens_expires_at_index` on `personal_access_tokens` (`expires_at`);
CREATE UNIQUE INDEX `currencies_code_unique` on `currencies` (`code`);
CREATE UNIQUE INDEX `stores_manager_id_code_unique` on `stores` (`manager_id`, `code`);
CREATE INDEX `stores_manager_id_is_active_index` on `stores` (`manager_id`, `is_active`);
CREATE INDEX `stores_manager_id_currency_id_index` on `stores` (`manager_id`, `currency_id`);
CREATE UNIQUE INDEX `ingredient_product_ingredient_id_product_id_unique` on `ingredient_product` (`ingredient_id`, `product_id`);
CREATE UNIQUE INDEX `plans_name_unique` on `plans` (`name`);
CREATE UNIQUE INDEX `ingredient_categories_manager_id_name_unique` on `ingredient_categories` (`manager_id`, `name`);
CREATE UNIQUE INDEX `managers_slug_unique` on `managers` (`slug`);
CREATE INDEX `managers_plan_id_index` on `managers` (`plan_id`);
CREATE UNIQUE INDEX `ingredients_manager_id_name_unique` on `ingredients` (`manager_id`, `name`);
CREATE INDEX `ingredients_manager_id_ingredient_category_id_index` on `ingredients` (`manager_id`, `ingredient_category_id`);

SET foreign_key_checks = 1;
